### ISSUE TITLE
Ai实现原理

### ISSUE THREAD

**Issue by zfman** [Reginer/Renju#1]
您好：
`Ai.jar`的源码有吗?AI实现原理可以大概说下吗？

**Comment by Reginer** [comment]
README里有Ai.jar的源码。

Ai是jni类，计算代码都是在C++里完成的。

**Comment by zfman** [comment]
我说的就是那个计算最佳位置的代码（c++）
README中的代码没有关键的函数

嘻嘻~

**Comment by Reginer** [comment]
我可以把原理告诉你 。用到几个五子棋的术语，有不知道的话，你搜索下。
玩家下一子后，先判断是否冲四。不是冲四，ai计算自己有没有VCF，之后计算有没有VCT，
计算玩家VCT，没有则根据棋型置换表做棋。
![search](https://user-images.githubusercontent.com/12568257/42547355-42068b78-84f4-11e8-8fba-2f4b1e7d428c.png)

**Comment by zfman** [comment]
好的👍

**Comment by yaojunqi** [comment]
是的，正式包的BuildConfig内容是重复的？
